USE [master]
GO

/****** Object:  Database [Proyecto_Inventario]    Script Date: 4/6/2020 4:31:35 PM ******/
CREATE DATABASE [Proyecto_Inventario]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Proyecto_Inventario', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Proyecto_Inventario.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Proyecto_Inventario_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Proyecto_Inventario_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Proyecto_Inventario].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Proyecto_Inventario] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET ARITHABORT OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Proyecto_Inventario] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Proyecto_Inventario] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Proyecto_Inventario] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Proyecto_Inventario] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET RECOVERY FULL 
GO

ALTER DATABASE [Proyecto_Inventario] SET  MULTI_USER 
GO

ALTER DATABASE [Proyecto_Inventario] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Proyecto_Inventario] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Proyecto_Inventario] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Proyecto_Inventario] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Proyecto_Inventario] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Proyecto_Inventario] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Proyecto_Inventario] SET  READ_WRITE 
GO

